<a href="https://colab.research.google.com/github/KurizuXX/Data-Science-Assessment/blob/main/evaluacion_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Evaluacion 1 - Programacion para la ciencia de datos

In [2]:
# IMPORTES
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [4]:
# Lectura de dataset

df = pd.read_csv('../data/googleplaystore.csv')
df_rev = pd.read_csv('../data/googleplaystore_user_reviews.csv')

In [5]:
# Lectura de df

df.head(5)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [6]:
# Lectura de df_rev

df_rev.head(5)

,App,Translated_Review,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity
0,10 Best Foods for You,I like eat delicious food. That's I'm cooking ...,Positive,1.00,0.533333
1,10 Best Foods for You,This help eating healthy exercise regular basis,Positive,0.25,0.288462
2,10 Best Foods for You,NaN,NaN,NaN,NaN
3,10 Best Foods for You,Works great especially going grocery store,Positive,0.40,0.875000
4,10 Best Foods for You,Best idea us,Positive,1.00,0.300000

In [7]:
# Union de Dataframes
# Se utiliza "pd.merge" junto con "on='App', how='inner'" para asegurarse que
# solo se incluyan las filas en las cuales la app sea la misma, es decir, que las reviews del dataframe2 correspondan con las apps del dataframe1

df_full = pd.merge(df, df_rev, on='App', how='inner')
df_full.head(5)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Translated_Review,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity
0,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,A kid's excessive ads. The types ads allowed a...,Negative,-0.250,1.000000
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,It bad >:(,Negative,-0.725,0.833333
2,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,like,Neutral,0.000,0.000000
3,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,NaN,NaN,NaN,NaN
4,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,I love colors inspyering,Positive,0.500,0.600000

## Ahora, con un df completo, podemos comenzar a trabajar.

- comenzamos haciendo una revision sencilla de los datos, para saber mas o menos con que trabajaremos

In [8]:
# info del df

df_full.info()

<class 'pandas.DataFrame'>
RangeIndex: 122662 entries, 0 to 122661
Data columns (total 17 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   App                     122662 non-null  str
 1   Category                122662 non-null  str
 2   Rating                  122622 non-null  float64
 3   Reviews                 122662 non-null  str
 4   Size                    122662 non-null  str
 5   Installs                122662 non-null  str
 6   Type                    122662 non-null  str
 7   Price                   122662 non-null  str
 8   Content Rating          122662 non-null  str
 9   Genres                  122662 non-null  str
 10  Last Updated            122662 non-null  str
 11  Current Ver             122662 non-null  str
 12  Android Ver             122662 non-null  str
 13  Translated_Review       72605 non-null   str
 14  Sentiment               72615 non-null   str
 15  Sentiment_Polarity      72615 non-null   float64
 16  Sentiment_Subjectivity  72615 non-null   float64
dtypes: float64(3), str(14)
memory usage: 15.9 MB

In [9]:
# descripcion del df

df_full.describe()

              Rating  Sentiment_Polarity  Sentiment_Subjectivity
count  122622.000000        72615.000000            72615.000000
mean        4.322405            0.157320                0.494162
std         0.284766            0.332652                0.240144
min         2.500000           -1.000000                0.000000
25%         4.200000            0.000000                0.380000
50%         4.400000            0.129167                0.509740
75%         4.500000            0.356250                0.633333
max         4.900000            1.000000                1.000000

- Una vez hecho esto, pasamos a identificar las columnas con valores faltantes

In [10]:
datos_faltantes = df_full.isnull().sum()
print(datos_faltantes)

App                           0
Category                      0
Rating                       40
Reviews                       0
Size                          0
Installs                      0
Type                          0
Price                         0
Content Rating                0
Genres                        0
Last Updated                  0
Current Ver                   0
Android Ver                   0
Translated_Review         50057
Sentiment                 50047
Sentiment_Polarity        50047
Sentiment_Subjectivity    50047
dtype: int64

- Ahora revisamos si tenemos datos duplicados

In [11]:
datos_duplicados = df_full.duplicated().sum
print(datos_duplicados)

<bound method Series.sum of 0         False
1         False
2         False
3         False
4         False
          ...
122657     True
122658     True
122659     True
122660     True
122661     True
Length: 122662, dtype: bool>

- Podemos notar que tenemos una gran cantidad de datos faltantes

In [14]:
#Primero para asegurar la integridad de los datos originales, se va a duplicar el Dataframe que vamos a usar, para tener disponible una copia del dataframe original
#en caso de que se necesite volver a él
df_copy = df_full.copy()

In [21]:
# Vamos a rellenar los datos faltantes de la columna Rating con la media de la columna
df_copy['Rating'] = df_copy['Rating'].fillna(df_copy['Rating'].mean())

In [28]:
# Manejo de datos faltantes columnas Sentiment y Sentiment_Polarity
# Segun parece las columnas relacionadas a Sentiment estan relacionadas con las reseñas y estan codificadas por medio de StandardScaler,
# por lo que se puede rellenar estos datos con la media de cada columna, asegurando que los datos  faltantes no afectan la distribucion de los datos
df_copy['Sentiment_Polarity'] = df_copy['Sentiment_Polarity'].fillna(df_copy['Sentiment_Polarity'].mean())
df_copy['Sentiment_Subjectivity'] = df_copy['Sentiment_Subjectivity'].fillna(df_copy['Sentiment_Subjectivity'].mean())

In [29]:
datos_faltantes_copia = df_copy.isnull().sum()
print(datos_faltantes_copia)

App                           0
Category                      0
Rating                        0
Reviews                       0
Size                          0
Installs                      0
Type                          0
Price                         0
Content Rating                0
Genres                        0
Last Updated                  0
Current Ver                   0
Android Ver                   0
Translated_Review         50057
Sentiment                 50047
Sentiment_Polarity            0
Sentiment_Subjectivity        0
dtype: int64

Los datos que quedan por rellenar corresponden a reseñas de las aplicaciones, las cuales no se pueden rellenar por medio de funciones de pandas, por lo que se debe tomar una decision si estas filas se deben conservar o eliminar